### ISSUE TITLE
Logo on Admin page isn't clickable

### ISSUE THREAD

**Issue by svishnevsky** [BelHardAcademy/AcademySite#3]
**Summary**

Logo on Admin page isn't clickable

**Steps to reproduce**

1) Open Admin page.

2) Click on Logo.
![bug_admin_logoclick](https://user-images.githubusercontent.com/2376915/31572739-3db52b24-b0b5-11e7-8e68-c3828afd1548.png)

**Expected result**

Redirect to home page.

**Actual result**

Nothing happens.

**Comment by AlexZvo** [comment]
Redirect to home page after click on logo
